asia_food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('delivery.urls')),
    path('', include('cart.urls')),
    path('', include('search_app.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_view, name='view_cart'),
    path('add/food/<int:food_id>/', views.add_food, name='add_food'),
    path('add/drink/<int:drink_id>/', views.add_drink, name='add_drink'),
    path('delete/food/<int:pk>/', views.food_item_delete, name='delete_food'),
    path('delete/drink/<int:pk>/', views.drink_item_delete, name='delete_drink'),
    path('cart/checkout/', views.checkout, name='checkout')
]

cart/models.py
from django.db import models
from delivery.models import Food, Drink


class CartOrder(models.Model):
    fio = models.CharField(max_length=100)
    address = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=12)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    time = models.DateTimeField(auto_now=True, auto_created=True, null=True)

    def __str__(self):
        return f'Order to {self.fio}'


class FoodCart(models.Model):
    foods = models.ManyToManyField(Food, through='FoodCartItem')
    session_key = models.CharField(max_length=40, null=True)


class FoodCartItem(models.Model):
    food_cart = models.ForeignKey(FoodCart, on_delete=models.SET_NULL, null=True)
    food = models.ForeignKey(Food, on_delete=models.DO_NOTHING)
    order = models.ForeignKey(CartOrder, on_delete=models.DO_NOTHING, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.food} - {self.quantity} portion'


class DrinkCart(models.Model):
    drinks = models.ManyToManyField(Drink, through='DrinkCartItem')
    session_key = models.CharField(max_length=40, null=True)


class DrinkCartItem(models.Model):
    drink_cart = models.ForeignKey(DrinkCart, on_delete=models.SET_NULL, null=True)
    drink = models.ForeignKey(Drink, on_delete=models.DO_NOTHING)
    order = models.ForeignKey(CartOrder, on_delete=models.DO_NOTHING, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.drink} - {self.quantity} portion'

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class OrderForm(forms.ModelForm):
    class Meta:
        model = models.CartOrder
        fields = ['fio', 'address', 'phone_number']
        widgets = {
            'fio': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'address': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-group'
            })
        }

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if len(phone_number) not in [9, 12]:
            raise ValidationError('Wrong number of digits')
        return phone_number

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models, forms
from delivery.models import Food, Drink


def food_item_delete(request, pk):
    food = get_object_or_404(Food, id=pk)
    food_item = models.FoodCartItem.objects.filter(food=food).first()
    food_item.delete()
    return redirect('cart:view_cart')


def drink_item_delete(request, pk):
    drink = get_object_or_404(Drink, id=pk)
    drink_item = models.DrinkCartItem.objects.filter(drink=drink).first()
    drink_item.delete()
    return redirect('cart:view_cart')


def cart_view(request):
    session_key = request.session.session_key
    food_cart = models.FoodCart.objects.filter(session_key=session_key).first()
    drink_cart = models.DrinkCart.objects.filter(session_key=session_key).first()
    if request.method == "POST":
        form = forms.OrderForm(request.POST)
        if food_cart:
            for food_item in food_cart.foodcartitem_set.all():
                food_quantity = request.POST.get(f'quantity{food_item.food.pk}')
                request.session[f'quantity{food_item.food.pk}'] = food_quantity

        if drink_cart:
            for drink_item in drink_cart.drinkcartitem_set.all():
                drink_quantity = request.POST.get(f'quantity{drink_item.drink.pk}')
                request.session[f'quantity{drink_item.drink.pk}'] = drink_quantity

        return render(request, 'cart/order_create.html', {'form': form})

    if food_cart:
        foods_cart = food_cart.foods.all()
    else:
        foods_cart = []

    if drink_cart:
        drinks_cart = drink_cart.drinks.all()
    else:
        drinks_cart = []

    return render(request,
                  'cart/cart.html',
                  {'foods_cart': foods_cart,
                   'drinks_cart': drinks_cart})


def add_food(request, food_id):
    if request.method == 'POST':
        food = get_object_or_404(Food, id=food_id)

        session_key = request.session.session_key
        if not session_key:
            request.session.save()

        food_cart = models.FoodCart.objects.filter(session_key=session_key).first()

        if not food_cart:
            food_cart = models.FoodCart.objects.create(session_key=session_key)

        food_item, created = models.FoodCartItem.objects.get_or_create(food_cart=food_cart,
                                                                       food=food,
                                                                       quantity=1)

        if not created:
            food_item.quantity += 1
            food_item.save()
        else:
            food_item.quantity = 1
            food_item.save()

        food_cart.foods.add(food)

    return redirect('cart:view_cart')


def add_drink(request, drink_id):
    if request.method == 'POST':
        drink = get_object_or_404(Drink, id=drink_id)

        session_key = request.session.session_key
        if not session_key:
            request.session.save()

        drink_cart = models.DrinkCart.objects.filter(session_key=session_key).first()
        if not drink_cart:
            drink_cart = models.DrinkCart.objects.create(session_key=session_key)

        drink_item, created = models.DrinkCartItem.objects.get_or_create(drink_cart=drink_cart,
                                                                         drink=drink,
                                                                         quantity=1)
        if not created:
            drink_item.quantity += 1
            drink_item.save()
        else:
            drink_item.quantity = 1
            drink_item.save()

        drink_cart.drinks.add(drink)

        return redirect('cart:view_cart')


def checkout(request):
    if request.method == 'POST':
        form = forms.OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            session_key = request.session.session_key

            food_cart = models.FoodCart.objects.filter(session_key=session_key).first()
            drink_cart = models.DrinkCart.objects.filter(session_key=session_key).first()

            total_price = 0
            if food_cart:
                for food_item in food_cart.foodcartitem_set.all():
                    food = food_item.food
                    food_item.quantity = request.session[f'quantity{food.pk}']
                    price = food.price * int(food_item.quantity)
                    total_price += price
                    order.total_price = total_price
                    order.save()

                    food_item.order = order
                    food_item.save()
                food_cart.delete()
            if drink_cart:
                for drink_item in drink_cart.drinkcartitem_set.all():
                    drink = drink_item.drink
                    drink_item.quantity = request.session[f'quantity{drink.pk}']
                    price = drink.price * int(drink_item.quantity)
                    total_price += price
                    order.total_price = total_price
                    order.save()

                    drink_item.order = order
                    drink_item.save()
                drink_cart.delete()

            order.save()
            total_price = order.total_price

            return render(request, 'cart/checkout.html', {'total_price': total_price})

        form = forms.OrderForm()
        return render(request, 'cart/order_create.html', {'form': form})

cart/templates/cart/cart.html
{% extends 'cart/base.html' %}
{% block title %}My Cart{% endblock %}

{% block content %}
<form action="{% url 'cart:view_cart' %}" method="POST">
    {% csrf_token %}
    <div class="cart-container">
        <h2>Shopping Cart</h2>
        <table class="cart-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for food in foods_cart %}
                <tr>
                    <td>{{ food.name }}</td>
                    <td><img src="{{ food.photo.url }}" alt="{{ food.name }}"></td>
                    <td>{{ food.price }}</td>
                    <td><input type="number" value="1" min="1" max="10" name="quantity{{ food.id }}"></td>
                    <td><a href="{% url 'cart:delete_food' food.id %}" class="delete button">Delete</a></td>
                </tr>
                {% endfor %}
                {% for drink in drinks_cart %}
                <tr>
                    <td>{{ drink.name }}</td>
                    <td><img src="{{ drink.photo.url }}" alt="{{ drink.name }}"></td>
                    <td>{{ drink.price }}</td>
                    <td><input type="number" value="1" min="1" max="10" name="quantity{{ drink.id }}"></td>
                    <td><a href="{% url 'cart:delete_drink' drink.id %}" class="delete button">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <form action="{% url 'cart:checkout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn-detail">Next</button>
        </form>
        <a href="{% url 'menu' %}" class="btn-detail">Back</a>
    </div>
</form>
{% endblock %}

cart/templates/cart/cart_confirm_delete.html
{% extends 'delivery/base.html' %}
{% block title %}Delete{% endblock %}

{% block content %}
    <div class="product-container">
        <h1>Delete {{ item }}</h1>
        <p>Are you sure you want to delete {{ item }}?</p>
        <form method="post">
            {% csrf_token %}
            <div class="actions">
                <button type="submit" class="delete button">Yes, delete</button>
                <a href="{% url 'cart:view_cart' %}" class="btn-back">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

cart/templates/cart/checkout.html
{% extends 'cart/base.html' %}
{% block title %}{% endblock %}

{% block content %}
<div class="cart-container">
    <h1>Thank You for Your Order!</h1>
    <p>Your order has been successfully placed.</p>
    <div class="total-price">
        <p>Total Price: {{total_price }}KGS</p>
    </div>
    <div class="form-group">
        <a href="{% url 'menu' %}" class="btn-detail">Back to Menu</a>
    </div>
</div>
{% endblock %}

cart/templates/cart/order_create.html
{% extends 'delivery/base.html' %}
{% block title %}Order To{% endblock %}

{% block content %}
    <form action="{% url 'cart:checkout' %}" method="POST" enctype="multipart/form-data" class="make-order-container">
        {% csrf_token %}
        <h1>Make order</h1>
        {% for field in form %}
            {{ field.label_tag }} {{ field }}<br>
            {{ field.errors }}
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn-detail">Checkout</button>
        </div>
    </form>
{% endblock %}