asia_food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('delivery.urls')),
    path('', include('cart.urls')),
    path('', include('search_app.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_view, name='view_cart'),
    path('add/food/<int:food_id>/', views.add_food, name='add_food'),
    path('add/drink/<int:drink_id>/', views.add_drink, name='add_drink'),
    path('delete/food/<int:pk>/', views.food_item_delete, name='delete_food'),
    path('delete/drink/<int:pk>/', views.drink_item_delete, name='delete_drink'),
    path('cart/checkout/', views.checkout, name='checkout')
]

delivery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MenuView.as_view(), name='menu'),
    path('sign_up', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('foods/<int:pk>', views.FoodDetailView.as_view(), name='food_detail'),
    path('drinks/<int:pk>', views.DrinkDetailView.as_view(), name='drink_detail'),
    path('foods/<int:pk>/update', views.FoodUpdateView.as_view(), name='food_update'),
    path('drinks/<int:pk>/update', views.DrinkUpdateView.as_view(), name='drink_update'),
    path('foods/<int:pk>/delete', views.FoodDeleteView.as_view(), name='food_delete'),
    path('drinks/<int:pk>/delete', views.DrinkDeleteView.as_view(), name='drink_delete'),
    path('make_order', views.OrderCreateView.as_view(), name='create_order'),
    path('make_order/products', views.OrderProductsCreateView.as_view(), name='ordered_products'),
    path('orders_list', views.OrderListView.as_view(), name='orders_list'),
    path('orders_list/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('orders_list/<int:pk>/', views.CartOrderDetailView.as_view(), name='cart_order_detail'),
    path('food_create', views.FoodCreateView.as_view(), name='food_create'),
    path('drink_create', views.DrinkCreateView.as_view(), name='drink_create')
]

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('result', views.SearchView.as_view(), name='search_result')
]

delivery/models.py
import os
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


IMAGES_ROOT = os.path.relpath(os.path.join(settings.MEDIA_ROOT, 'images'))


class CustomerUser(AbstractUser):
    ...


class FoodType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Food(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    weight = models.DecimalField(max_digits=3, decimal_places=2)
    photo = models.ImageField(upload_to=IMAGES_ROOT, null=True)
    type = models.ForeignKey(FoodType, on_delete=models.DO_NOTHING, null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return self.name


class Drink(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    volume = models.DecimalField(max_digits=6, decimal_places=2)
    photo = models.ImageField(upload_to=IMAGES_ROOT, null=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    fio = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=12)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    time = models.DateTimeField(auto_now=True, auto_created=True, null=True)

    def __str__(self):
        return f'Order to name {self.fio}'


class OrderFood(models.Model):
    food = models.ForeignKey(Food, on_delete=models.DO_NOTHING)
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=8, decimal_places=2, null=True)

    def __str__(self):
        return f'Order: {self.food} Quantity:{self.quantity}'


class OrderDrink(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.DO_NOTHING)
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=8, decimal_places=2, null=True)

    def __str__(self):
        return f'Order: {self.drink} Quantity:{self.quantity}'

delivery/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from . import models


class CustomerUserForm(UserCreationForm):
    class Meta:
        model = models.CustomerUser
        fields = ['first_name', 'last_name', 'email', 'username']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-group'
            }),
            'username': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'password': forms.PasswordInput(attrs={
                'class': 'form-group'
            })
        }


class FoodForm(forms.ModelForm):
    type = forms.ModelChoiceField(queryset=models.FoodType.objects.all(),
                                  widget=forms.Select(attrs={
                                      'class': 'form-group'
                                  }))
    new_food_type = forms.CharField(max_length=100, required=False)

    class Meta:
        model = models.Food
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-group'
            }),
            'weight': forms.NumberInput(attrs={
                'class': 'form-group'
            }),
            'photo': forms.FileInput(attrs={
                'class': 'form-group'
            }),
            'description': forms.TextInput(attrs={
                'class': 'form-group'
            })
        }

    def __init__(self, *args, **kwargs):
        super(FoodForm, self).__init__(*args, **kwargs)
        self.fields['type'].required = False
        self.fields = {
            'name': self.fields['name'],
            'price': self.fields['price'],
            'weight': self.fields['weight'],
            'type': self.fields['type'],
            'new_food_type': self.fields['new_food_type'],
            'photo': self.fields['photo'],
            'description': self.fields['description'],
        }


class DrinkForm(forms.ModelForm):
    class Meta:
        model = models.Drink
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-group'
            }),
            'volume': forms.NumberInput(attrs={
                'class': 'form-group'
            }),
            'photo': forms.FileInput(attrs={
                'class': 'form-group'
            })
        }


class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ['fio', 'address', 'phone_number']
        widgets = {
            'fio': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'address': forms.TextInput(attrs={
                'class': 'form-group'
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-group'
            })
        }

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if len(phone_number) not in [9, 12]:
            raise ValidationError('Wrong number of digits')
        return phone_number

delivery/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import (ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView, TemplateView)
from django.urls import reverse_lazy
from django.views import View
from . import models, utils, forms
from cart.models import CartOrder


class SignUpView(CreateView):
    model = models.CustomerUser
    template_name = 'delivery/sign_up.html'
    form_class = forms.CustomerUserForm
    success_url = reverse_lazy('menu')


def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            redirect('menu')

    return render(request, 'delivery/sign_in.html')


def log_out(request):
    logout(request)
    return redirect('')


class MenuView(ListView):
    model = models.FoodType
    template_name = 'delivery/menu.html'
    context_object_name = 'food_types'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        food_types = context['food_types']
        foods_by_type = {}
        for food_type in food_types:
            foods_by_type[food_type] = food_type.food_set.all()
        context['foods_by_type'] = foods_by_type
        context['drinks'] = models.Drink.objects.all()
        return context


class FoodDetailView(DetailView):
    model = models.Food
    template_name = 'delivery/food.html'
    context_object_name = 'food'


class DrinkDetailView(DetailView):
    model = models.Drink
    template_name = 'delivery/drink.html'
    context_object_name = 'drink'


class FoodCreateView(CreateView):
    model = models.Food
    template_name = 'delivery/food_create.html'
    form_class = forms.FoodForm
    success_url = reverse_lazy('menu')

    def form_valid(self, form):
        food_type = form.cleaned_data['type']
        new_food_type = form.cleaned_data['new_food_type']
        if new_food_type:
            food_type = models.FoodType.objects.create(name=new_food_type)
        form.instance.type = food_type

        return super().form_valid(form)


class DrinkCreateView(CreateView):
    model = models.Drink
    template_name = 'delivery/drink_create.html'
    form_class = forms.DrinkForm
    success_url = reverse_lazy('menu')


class FoodUpdateView(UpdateView):
    model = models.Food
    template_name = 'delivery/food_update.html'
    form_class = forms.FoodForm
    success_url = reverse_lazy('menu')


class DrinkUpdateView(UpdateView):
    model = models.Drink
    template_name = 'delivery/drink_update.html'
    form_class = forms.DrinkForm
    success_url = reverse_lazy('menu')


class FoodDeleteView(DeleteView):
    model = models.Food
    success_url = reverse_lazy('menu')


class DrinkDeleteView(DeleteView):
    model = models.Drink
    success_url = reverse_lazy('menu')


class OrderCreateView(TemplateView):
    template_name = 'delivery/create_order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.OrderForm()
        return context

    def post(self, request):
        form = forms.OrderForm(request.POST)
        if form.is_valid():
            request.session['fio'] = form.cleaned_data['fio']
            request.session['address'] = form.cleaned_data['address']
            request.session['phone_number'] = form.cleaned_data['phone_number']
            return redirect('ordered_products')

        return render(request, self.template_name, {'form': form})


class OrderProductsCreateView(View):

    @staticmethod
    def get(request):
        foods = models.Food.objects.all()
        drinks = models.Drink.objects.all()
        return render(request,
                      'delivery/ordered_products.html',
                      {'foods': foods, 'drinks': drinks}
                      )

    @staticmethod
    def post(request):
        food_ids = request.POST.getlist('foods')
        drink_ids = request.POST.getlist('drinks')
        order = utils.create_order(request.session['fio'],
                                   request.session['address'],
                                   request.session['phone_number'],
                                   0)
        total_price = 0

        for food_id in food_ids:
            food = get_object_or_404(models.Food, id=food_id)
            order_food = utils.create_order_food(food, order,
                                                 request.POST[f'quantity{food_id}'])
            total_price += order_food.price
            order_food.save()

        for drink_id in drink_ids:
            drink = get_object_or_404(models.Drink, id=drink_id)
            order_drink = utils.create_order_drink(drink, order,
                                                   request.POST[f'quantity{drink_id}'])
            total_price += order_drink.price
            order_drink.save()

        order.total_price = total_price
        order.save()

        return redirect('menu')


class OrderListView(ListView):
    model = models.Order
    template_name = 'delivery/orders_list.html'
    context_object_name = 'orders'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_orders'] = CartOrder.objects.all()
        return context


class OrderDetailView(DetailView):
    model = models.Order
    template_name = 'delivery/orders_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.get_object()
        order_foods = order.orderfood_set.all()
        order_drinks = order.orderdrink_set.all()
        context['order_foods'] = order_foods
        context['order_drinks'] = order_drinks
        context['total_price'] = order.total_price
        return context


class CartOrderDetailView(DetailView):
    models = CartOrder
    queryset = CartOrder.objects.all()
    template_name = 'delivery/orders_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_order = self.get_object()
        foods_item = cart_order.foodcartitem_set.all()
        drinks_item = cart_order.drinkcartitem_set.all()
        context['foods_item'] = foods_item
        context['drinks_item'] = drinks_item
        context['total_price'] = cart_order.total_price
        return context

delivery/templates/delivery/create_order.html
{% extends 'delivery/base.html' %}
{% block title %}make order{% endblock %}

{% block content %}
    <form action="{% url 'create_order' %}" method="POST" enctype="multipart/form-data" class="make-order-container">
        {% csrf_token %}
        <h1>Make order</h1>
            {{ form }}
        <div class="form-group">
            <input type="submit" value="Next" class="btn-next">
        </div>
    </form>
{% endblock %}

delivery/templates/delivery/drink.html
{% extends 'delivery/base.html' %}
{% block title %}
    {{ drink.name }}
{% endblock %}

{% block content %}
<div class="product-container">
    <h1>{{ drink.name }} info</h1>
    <div class="product-info">
        <div class="product-image">
            <img src="{{ drink.photo.url }}">
        </div>
        <div class="product-description">
            <h2>{{ drink.name }}</h2>
            <p>price: {{ drink.price }}</p>
            <p>volume: {{ drink.volume }}</p>
            <div class="actions">
                <a href="{% url 'drink_update' drink.id %}" class="btn-update">Update</a>
                <a href="{% url 'drink_delete' drink.id %}" class="btn-delete">Delete</a>
                <a href="{% url 'menu' %}" class="btn-back">Back</a>
                <form action="{% url 'cart:add_drink' drink.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn-submit">Add to Cart</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

delivery/templates/delivery/drink_confirm_delete.html
{% extends 'delivery/base.html' %}
{% block title %}Delete{% endblock %}

{% block content %}
    <div class="product-container">
        <h1>Delete {{ drink.name }}</h1>
        <p>Are you sure you want to delete "{{ drink.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <div class="actions">
                <button type="submit" class="btn-delete">Yes, delete</button>
                <a href="{% url 'drink_detail' drink.id %}" class="btn-back">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

delivery/templates/delivery/drink_update.html
{% extends 'delivery/base.html' %}
{% block title %}Update{% endblock %}

{% block content %}
  <form action="{% url 'drink_update' drink.id %}" method="POST"  enctype="multipart/form-data" class="update-product-container">
      {% csrf_token %}
          <h1>Update</h1>
          <form class="update-product-form">
              {{ form }}
              <div class="form-group">
                  <button type="submit" class="btn-update">Update</button>
              </div>
          </form>
      </div>
  </form>
{% endblock %}

delivery/templates/delivery/food.html
{% extends 'delivery/base.html' %}
{% block title %}
    {{ food.name }}
{% endblock %}

{% block content %}
<div class="product-container">
    <h1>{{ food.name }} info</h1>
    <div class="product-info">
        <div class="product-image">
            <img src="{{ food.photo.url }}">
        </div>
        <div class="product-description">
            <h2>{{ food.name }}</h2>
            <p><strong>price: {{ food.price }}</strong></p>
            <p><strong>weight: {{ food.weight }}</strong></p>
            <p><strong>description: {{ food.description }}</strong></p>
            <div class="actions">
                <a href="{% url 'food_update' food.id %}" class="btn-update">Update</a>
                <a href="{% url 'food_delete' food.id %}" class="btn-delete">Delete</a>
                <a href="{% url 'menu' %}" class="btn-back">Back</a>
                <form action="{% url 'cart:add_food' food.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn-submit">Add to cart</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

delivery/templates/delivery/food_confirm_delete.html
{% extends 'delivery/base.html' %}
{% block title %}Delete{% endblock %}

{% block content %}
    <div class="product-container">
        <h1>Delete {{ food.name }}</h1>
        <p>Are you sure you want to delete "{{ food.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <div class="actions">
                <button type="submit" class="btn-delete">Yes, delete</button>
                <a href="{% url 'food_detail' food.id %}" class="btn-back">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

delivery/templates/delivery/food_create.html
{% extends 'delivery/base.html' %}
{% block title %}Add food{% endblock %}

{% block content %}
    <form action="{% url 'food_create' %}" method="POST"  enctype="multipart/form-data" class="update-product-container">
      {% csrf_token %}
          <h1>Add food</h1>
              {{ form }}
              <div class="form-group">
                  <button type="submit" class="btn-update">Add</button>
              </div>
    </form>
{% endblock %}

delivery/templates/delivery/food_update.html
{% extends 'delivery/base.html' %}
{% block title %}Update{% endblock %}

{% block content %}
    <form action="{% url 'food_update' food.id %}" method="POST"  enctype="multipart/form-data" class="update-product-container">
      {% csrf_token %}
          <h1>Update</h1>
          <form class="update-product-form">
              {{ form }}
              <div class="form-group">
                  <button type="submit" class="btn-update">Update</button>
              </div>
          </form>
      </div>
    </form>
{% endblock %}

delivery/templates/delivery/menu.html
{% extends 'delivery/base.html' %}
{% block title %}Menu{% endblock %}

{% block content %}
<header>
    <div class="container">
        <h1>Menu</h1>
        <nav>
            <div class="actions">
                <a href="{% url 'create_order' %}" class="btn">Make Order</a>
                <a href="{% url 'orders_list' %}" class="btn">Orders List</a>
                <a href="{% url 'food_create' %}" class="btn">Add Food</a>
                <a href="{% url 'drink_create' %}" class="btn">Add Drink</a>
                <a href="{% url 'cart:view_cart' %}" class="btn">My Cart</a>
            </div>
        </nav>
    </div>
    <form class="search-form" action="{% url 'search:search_result' %}" method="GET">
        <input type="text" name="query" placeholder="Search...">
        <button type="submit">Search</button>
    </form>
</header>


{% for food_type, foods in foods_by_type.items %}
    <h2>{{ food_type.name }}</h2>
    <div class="product-grid">
    {% for food in foods %}
        <div class="product">
            <img src="{{ food.photo.url }}" alt="{{ food.name }}">
            <h2>{{ food.name }}</h2>
            <p class="price">price: {{ food.price }}</p>
            <a href="{% url 'food_detail' food.pk %}" class="btn-detail">detail</a><br>
            <form action="{% url 'cart:add_food' food.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn-detail">Add to cart</button>
            </form>
        </div>
    {% endfor %}
    </div>
{% endfor %}
    <h2>Drinks</h2>
    <div class="product-grid">
        {% for drink in drinks %}
            <div class="product">
                <img src="{{ drink.photo.url }}" alt="{{ drink.name }}">
                <h2>{{ drink.name }}</h2>
                <p class="price">price: {{ drink.price }}</p>
                <a href="{% url 'drink_detail' drink.pk %}" class="btn-detail">detail</a><br>
                <form action="{% url 'cart:add_drink' drink.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn-detail">Add to Cart</button>
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock %}

delivery/templates/delivery/ordered_drinks.html
{% extends 'delivery/base.html' %}
{% block title %}Order{% endblock %}

{% block content %}
    <h1>Order Food & Drinks</h1>
    <form action="{% url 'ordered_drinks' %}" method="post">
    {% csrf_token %}
        {% for drink in drinks %}
            <div class="menu-item">
                <input type="checkbox" id="{{ drink.name }}" name="drink">
                <label for="{{ drink.name }}">
                    <img src="{{ drink.photo.url }}" alt="{{ drink.name }}">
                    <h2>{{ drink.name }}</h2>
                    <p>{{ drink.price }}</p>
                </label>
                <input type="number" name="drink_quantity" value="1" min="1" max="10">
            </div>
        {% endfor %}
        <button type="submit" class="btn-submit">Submit Order</button>
    </form>
{% endblock %}

delivery/templates/delivery/ordered_products.html
{% extends 'delivery/base.html' %}
{% block title %}Order{% endblock %}

{% block content %}
    <h1>Order Food & Drinks</h1>
    <form action="{% url 'ordered_products' %}" method="post">
    {% csrf_token %}
        {% for food in foods %}
            <div class="menu-item">
                <input type="checkbox" id="{{ food.name }}" name="foods" value="{{ food.id }}">
                <label for="{{ food.name }}">
                    <img src="{{ food.photo.url }}" alt="{{ food.name }}">
                    <h2>{{ food.name }}</h2>
                    <p>{{ food.price }}</p>
                </label>
                <input type="number" name="quantity{{ food.id }}" value="1" min="1" max="10">
            </div>
        {% endfor %}
        {% for drink in drinks %}
            <div class="menu-item">
                <input type="checkbox" id="{{ drink.name }}" name="drinks" value="{{ drink.id }}">
                <label for="{{ drink.name }}">
                    <img src="{{ drink.photo.url }}" alt="{{ drink.name }}">
                    <h2>{{ drink.name }}</h2>
                    <p>{{ drink.price }}</p>
                </label>
                <input type="number" name="quantity{{ drink.id }}" value="1" min="1" max="10">
            </div>
        {% endfor %}
        <button type="submit" class="btn-submit">Submit Order</button>
    </form>
{% endblock %}

delivery/templates/delivery/orders_detail.html
{% extends 'delivery/base.html' %}
{% block title %}Order list{% endblock %}

{% block content %}
<div class="order-table-container">
    <h1>Order List</h1>
    <table class="order-table">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Photo</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                        {% for order_food in order_foods %}
                        <tr>
                            <td>{{ order_food.food.name }}</td>
                            <td><img src="{{ order_food.food.photo.url }}" alt="{{ order_food.food.name }}"></td>
                            <td>{{ order_food.quantity }}</td>
                            <td>{{ order_food.price }} KGS</td>
                        </tr>
                        {% endfor %}
                        {% for order_drink in order_drinks %}
                        <tr>
                            <td>{{ order_drink.drink.name }}</td>
                            <td><img src="{{ order_drink.drink.photo.url }}" alt="{{ order_drink.drink.name }}"></td>
                            <td>{{ order_drink.quantity }}</td>
                            <td>{{ order_drink.price }} KGS</td>
                        </tr>
                        {% endfor %}
                        {% for food_item in foods_item %}
                        <tr>
                            <td>{{ food_item.food.name }}</td>
                            <td><img src="{{ food_item.food.photo.url }}" alt="{{ food_item.food.name }}"></td>
                            <td>{{ food_item.quantity }}</td>
                            <td>{{ food_item.food.price }} KGS</td>
                        </tr>
                        {% endfor %}
                        {% for drink_item in drinks_item %}
                        <tr>
                            <td>{{ drink_item.drink.name }}</td>
                            <td><img src="{{ drink_item.drink.photo.url }}" alt="{{ drink_item.drink.name }}"></td>
                            <td>{{ drink_item.quantity }}</td>
                            <td>{{ drink_item.drink.price }} KGS</td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
    <div class="total-price">
        <p>Total Price: {{total_price }}KGS</p>
    </div>
</div>
{% endblock %}

delivery/templates/delivery/sign_in.html
{% extends 'delivery/base.html' %}
{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="sign-up-container">
        <h2>Sign In</h2>
        <form action="{% url 'sign_up' %}" class="signup-form" method="POST">
            {% csrf_token %}
            <p><input type="text" name="username" placeholder="username" class="form-group"></p>
            <p><input type="text" name="password" placeholder="password" class="form-group"></p>
            <button type="submit">Sign In</button>
        </form>
    </div>
{% endblock %}

delivery/templates/delivery/sign_up.html
{% extends 'delivery/base.html' %}
{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="sign-up-container">
        <h2>Sign Up</h2>
        <form action="{% url 'sign_up' %}" class="signup-form">
            {{ form }}
        </form>
    </div>
{% endblock %}